// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpq79Mlc5bGLC004Uee3V9fj0UNAgs448',
    appId: '1:661039624157:web:b30043e80ec74d67259034',
    messagingSenderId: '661039624157',
    projectId: 'roomies-attempt-four',
    authDomain: 'roomies-attempt-four.firebaseapp.com',
    storageBucket: 'roomies-attempt-four.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4qXw5IlvLXmfstmAKUtzcRzTZF7va4Fo',
    appId: '1:661039624157:ios:7e3d556ffe0607d3259034',
    messagingSenderId: '661039624157',
    projectId: 'roomies-attempt-four',
    storageBucket: 'roomies-attempt-four.firebasestorage.app',
    iosBundleId: 'com.example.roomies',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4qXw5IlvLXmfstmAKUtzcRzTZF7va4Fo',
    appId: '1:661039624157:ios:7e3d556ffe0607d3259034',
    messagingSenderId: '661039624157',
    projectId: 'roomies-attempt-four',
    storageBucket: 'roomies-attempt-four.firebasestorage.app',
    iosBundleId: 'com.example.roomies',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS8R4E7SKP3okDxMABSgVd8DSz_-bksn4',
    appId: '1:661039624157:android:53fdde5f7c25d736259034',
    messagingSenderId: '661039624157',
    projectId: 'roomies-attempt-four',
    storageBucket: 'roomies-attempt-four.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpq79Mlc5bGLC004Uee3V9fj0UNAgs448',
    appId: '1:661039624157:web:d95f564ea7d1e62f259034',
    messagingSenderId: '661039624157',
    projectId: 'roomies-attempt-four',
    authDomain: 'roomies-attempt-four.firebaseapp.com',
    storageBucket: 'roomies-attempt-four.firebasestorage.app',
  );

}